# Build the manager binary
FROM golang:1.21 as builder

WORKDIR /workspace
# Copy the Go Modules manifests
COPY ./backend/go.mod go.mod
COPY ./backend/go.sum go.sum

RUN go mod download


COPY ./backend ./
RUN CGO_ENABLED=1 go build -a -o server ./cmd/


FROM golang:1.21

WORKDIR /

COPY --from=builder /workspace/prod.db /prod.db
COPY --from=builder /workspace/server /server

EXPOSE 8080

ENTRYPOINT ["/server"]