import Navbar from "@/components/Navbar";
import "../globals.css";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";

const quickSand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className={"bg-gray-900 " + quickSand.className}>
      <Navbar />
      <div className="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
        {children}
      </div>
    </section>
  );
}
